name: Nuget Push

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101

    - name: Build with dotnet
      run: |
        cd Chakra.Core
        dotnet build --configuration Release

    - name: Package Chakra.Core
      run: |  
        cd Chakra.Core
        dotnet pack -c Release -o out

    - name: Publish Chakra.Core to Nuget
      run: |
        cd Chakra.Core
        dotnet nuget push ./out/$(ls ./out) -s https://api.nuget.org/v3/index.json -k ${APIKEY}  
      env:
        APIKEY: ${{ secrets.NUGET_APIKEY }} 
